### PR TITLE
Added backend messaging functionality to the contact form 

### PR DESCRIPTION
**Pull request by AyushSharma72**
hey @aswathcm29  i just added the backend by which you can receive the messages on your email 

**Like this**
WhatsApp Image 2024-10-02 at 13 51 03_21e094bd

if it's okay please merge 🙏🙏

### CODE REVIEW

**Comment by aswathcm29** [comment]
That's a great add-on, @AyushSharma72 ! However, I would like you to follow the previous coding methods for keeping routes in the backend and to use Axios instead of Fetch in the frontend.

**Comment by AyushSharma72** [comment]
> That's a great add-on, @AyushSharma72 ! However, I would like you to follow the previous coding methods for keeping routes in the backend and to use Axios instead of Fetch in the frontend.

i will replace fetch with axios now

**Comment by AyushSharma72** [comment]
i have done what you asked for please kindly merge if you are satisfied @aswathcm29

**Comment by AyushSharma72** [comment]
Hey @aswathcm29 can you please merge this pr also I want to request you to mark this issue(#55 ) level 3

**Comment by AyushSharma72** [comment]
> Hey @aswathcm29 can you please merge this pr also I want to request you to mark this issue(#55 ) level 3

please add level tag before merging or else points will not be allocated to me for the pr

**Comment by sanjay-kv** [comment]
@aswathcm29 hey we have requested to add me in to the repo to manage the labels. 
you have not following any guidelines we provided.

**Comment by aslams2020** [comment]
This PR has been merged by the GSSoC team 
here - https://github.com/sanjay-kv/Open-source-Practice/pull/1419


 Don't add labels to it now.You'll get the points in the leaderboard update.

**Pull request closed without merging**
