### PR TITLE
Addition Of All Contributors | Issue #86

### PR DESCRIPTION
**Pull request by Shariq2003**
Completed #86 

image

### CODE REVIEW

**Comment by Shariq2003** [comment]
@aswathcm29 please review this PR, its in pending state since 3 days

**Comment by Shariq2003** [comment]
@aswathcm29 please review PR and merge

**Comment by Shariq2003** [comment]
@aswathcm29 please add levels to this PR.

**Comment by Shariq2003** [comment]
@MastanSayyad sir, sorry for disturbing again, but you just have to add labels, pleaseeeeeeee.

**Comment by MastanSayyad** [comment]
I have no access to the repo @aswathcm29 kindly review the PR, add labels and as me as a collaborator

**Pull request merged**
