### PR TITLE
password show hide eye icon button add : completing the issue #40 which is assigned to me.

### PR DESCRIPTION
**Pull request by VinayLodhi1712**
Password show hide icon added and it will working fine on both full screen and responsive mode correctly .  completing the issue #40 which is assigned to me.

additionaly Sir i want to add things like that if you add the label mainly gssoc extended and hactoberfest and the level of this issue it will be good for me and help me to grow on the leaderboard also.

eye 3
eye 2
eye 1

### CODE REVIEW

**Comment by aswathcm29** [comment]
I think there might be some issue that causes on the building process @VinayLodhi1712 ! 
image

This is what i got when the build failed...and hence make sure to have made necessary changes to build properly !

**Comment by VinayLodhi1712** [comment]
ok sry for that i will see what is the problem and inform you when it is done.

**Comment by VinayLodhi1712** [comment]
so i have done actually the problem is that 
while adding icons Fa-eye i have firstly try normal fontawesome but it is not looking good so than i try with react-icons and i forget to remove the import statement of font-awesome. so now i have remove that 

and Now @aswathcm29 you can check once and it will done I think.

**Comment by aswathcm29** [comment]
No not yet cleared @VinayLodhi1712 ! still its stuck with the same issue ! kindly do look after it

**Comment by VinayLodhi1712** [comment]
can you check once again if it will work then tell me another wise i will fork and clone again and make changes again and create pull request again. Sry for inconvinience.

**Comment by aswathcm29** [comment]
> can you check once again if it will work then tell me another wise i will fork and clone again and make changes again and create pull request again. Sry for inconvinience.

Still stuck with the same issue @VinayLodhi1712 ..ahemm

**Comment by VinayLodhi1712** [comment]
So ok Sry for the convinience, Now i am again fork and clone your website and write code again with new branch and new pull request. so i think that will not create problem.

**Comment by VinayLodhi1712** [comment]
can you close this by your own way if you can because it is not showing accepted on hactoberfest. If you are free then plz look into this it will help me

**Pull request closed without merging**
