### PR TITLE
made the register page responsive

### PR DESCRIPTION
**Pull request by AyushSharma72**
i just improved the responsiveness of the register page 

before:

Screenshot 2024-10-02 113949

Now:
Screenshot 2024-10-02 122817

### CODE REVIEW

**Comment by AyushSharma72** [comment]
thank you

**Comment by AyushSharma72** [comment]
@aswathcm29  please add level to this pr  else no points will be allocated for this pr

**Comment by hemanthkumar-21** [comment]
@aswathcm29   i am one of the program managers of gssoc-ext. can you please add relevant level label for this pr.

**Comment by aslams2020** [comment]
This PR has been merged by the GSSoC team 
here - https://github.com/sanjay-kv/Open-source-Practice/pull/1419


 Don't add labels to it now.You'll get the points in the leaderboard update.

**Comment by AyushSharma72** [comment]
> This PR has been merged by the GSSoC team here - [sanjay-kv/Open-source-Practice#1419](https://github.com/sanjay-kv/Open-source-Practice/pull/1419)
> 
> Don't add labels to it now.You'll get the points in the leaderboard update.

you havent add any level

**Comment by aslams2020** [comment]
Added there. 
No need to add here.

**Pull request merged**
