### PR TITLE
feat:#60 added

### PR DESCRIPTION
**Pull request by itznayan**
https://github.com/user-attachments/assets/da5d9292-1d1f-483f-b5f9-9547cb29100a

### CODE REVIEW

**Comment by aswathcm29** [comment]
Hey @itznayan ! It's absolutely great but i could see in **journals** and **profile** alone seems like there's a shake effect because of dynamic content generation in the pages ! Is there any possibility to fix that like it works for **Home** and **Contactus**

**Comment by itznayan** [comment]
@aswathcm29 i don't get it please attach video . i am not able to understand problem

**Comment by itznayan** [comment]
@aswathcm29 i understand the issue but it's not due to navbar which i created. please approve this PR . i am generating new issue for this bug fix .

**Comment by aswathcm29** [comment]
> @aswathcm29 i understand the issue but it's not due to navbar which i created. please approve this PR . i am generating new issue for this bug fix .

Okay let me merge it !

**Comment by itznayan** [comment]
@aswathcm29 please correct label it should be level1 please remove level-1 dash from label

**Pull request merged**
